apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-1

vpc:
  id: "vpc-0a4fbb1ada9f90f3d"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.165.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    private:
      us-east-1a:
        id: "subnet-02fa1f7d08355797c"
        cidr: "192.165.2.0/24" # (optional, must match CIDR used by the given subnet)
        
     public:
        us-east-1a:
        id: "subnet-0844e5c49c6e83c1f"
        cidr: "192.165.0.0/24" # (optional, must match CIDR used by the given subnet)
        
        us-east-1a:
        id: "subnet-06f19a8ddc15420cc"
        cidr: "192.165.1.0/24" # (optional, must match CIDR used by the given subnet)
        
        us-east-1b:
        id: "subnet-004e03ae798b535ec"
        cidr: "192.165.3.0/24" # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/.ssh/id_rsa.pub
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
