apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
